language: python
python:
  - "3.6"
install:
  - pip install -r requirements_testing.txt
script:
  # `set -e` will make script to stop if tests fail or anything else
  - pip freeze
  - set -e
  - pytest

  # set ZAPPA_STAGE env var depending on current branch
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export ZAPPA_STAGE=dev; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export ZAPPA_STAGE=prod; fi

  # uninstall testing requirements and reinstall base requirements to keep
  # zappa package as small as possible
  - pip uninstall -r requirements_testing.txt -y
  - pip install -r requirements.txt

  # test if .zip file can be created
  - zappa package $ZAPPA_STAGE

  # set aws credentials from env vars set in web interface
  - mkdir -p ~/.aws
  - echo "[mislavcimpersak]" >> ~/.aws/credentials
  - echo "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
  - echo "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials

  # try to update, if the command fails do the initial deploy
  - zappa update $ZAPPA_STAGE || zappa deploy $ZAPPA_STAGE;
