language: python
python:
  - "3.6"
install:
  - pip install -r requirements_testing.txt
script:
  # `set -e` will make script to stop if tests fail or anything else
  - set -e
  - pytest
  - pip uninstall -r requirements_testing.txt -y
  - pip install -r requirements.txt
  - mkdir -p ~/.aws
  - echo "[mislavcimpersak]" >> ~/.aws/credentials
  - echo "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
  - echo "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export ZAPPA_STAGE=dev; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export ZAPPA_STAGE=prod; fi
  - if
      zappa status $ZAPPA_STAGE;
    then
      zappa update $ZAPPA_STAGE;
    else
      zappa deploy $ZAPPA_STAGE;
    fi
